force-app/main/default/objects/Trigger_Action__mdt/Trigger_Action__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Actions for</description>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Action__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <inlineHelpText>The name of the Apex class for this action.
The action must implement the seven20.TriggerAction interface</inlineHelpText>
    <label>Apex Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Invoke_Order__c.field-meta.xml
<CustomField>
    <fullName>Invoke_Order__c</fullName>
    <inlineHelpText>The order this action will be called within the trigger context</inlineHelpText>
    <label>Invoke Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Is this trigger action active?
For seven20 actions, modify this value at your own risk</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <inlineHelpText>The namespace of the called trigger action (if one is present)</inlineHelpText>
    <label>Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Trigger_Context__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Context__c</fullName>
    <inlineHelpText>What context should this action be invoked in?</inlineHelpText>
    <label>Trigger Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_DELETE</fullName>
                <default>true</default>
                <label>BEFORE_DELETE</label>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Trigger_Object__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Object__c</fullName>
    <label>Trigger Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Trigger_Actions</relationshipLabel>
    <relationshipName>Trigger_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Trigger_Object_Special__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Object_Special__c</fullName>
    <description>Objects unsupported by Entity Definition lookups, but which can still have Triggers associated with them</description>
    <inlineHelpText>If the object type isn&apos;t available via the object lookup, it can be added here</inlineHelpText>
    <label>Trigger Object (Special)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EmailMessage</fullName>
                <label>Email Message</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandler.cls
public without sharing class TriggerHandler {
    private static final List<Schema.SObjectType> SPECIAL_SOBJECT_TYPES = new List<Schema.SObjectType>{
        Task.getSObjectType(),
        EmailMessage.getSObjectType(),
        Event.getSObjectType(),
        User.getSObjectType()
    };

    @TestVisible
    private static Set<Id> disabledActions = new Set<Id>();
    @TestVisible
    private static Boolean disableAllActions = false;

    @SuppressWarnings('PMD.ExcessiveParameterList')
    public static void run(
        List<SObject> oldList,
        List<SObject> newList,
        Map<Id, SObject> oldMap,
        Map<Id, SObject> newMap,
        System.TriggerOperation operationType
    ) {
        if (disableAllActions) {
            return;
        }

        Schema.SObjectType triggerSObjectType = getTriggerSObjectType(oldList, newList);
        List<TriggerInvokableAction> triggerActions = getTriggerActions(
            triggerSObjectType,
            operationType
        );

        invokeTriggerActions(triggerActions, oldList, newList, oldMap, newMap, operationType);
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    @TestVisible
    private static void invokeTriggerActions(
        List<TriggerInvokableAction> invokableActions,
        List<SObject> oldList,
        List<SObject> newList,
        Map<Id, SObject> oldMap,
        Map<Id, SObject> newMap,
        System.TriggerOperation operationType
    ) {
        for (TriggerInvokableAction action : invokableActions) {
            action.run(oldList, newList, oldMap, newMap, operationType);
        }
    }

    @TestVisible
    private static List<TriggerInvokableAction> getTriggerActions(
        Schema.SObjectType objectType,
        System.TriggerOperation operationType
    ) {
        List<Trigger_Action__mdt> actionMetadata = getTriggerActionMetadata(
            objectType,
            operationType
        );

        List<TriggerInvokableAction> invokableActions = new List<TriggerInvokableAction>();

        for (Trigger_Action__mdt metadataRecord : actionMetadata) {
            if (!disabledActions.contains(metadataRecord.Id)) {
                invokableActions.add(
                    new TriggerInvokableAction(
                        metadataRecord.Namespace__c,
                        metadataRecord.Apex_Class_Name__c
                    )
                );
            }
        }

        return invokableActions;
    }

    @TestVisible
    private static Schema.SObjectType getTriggerSObjectType(
        List<SObject> oldList,
        List<SObject> newList
    ) {
        return newList == null ? oldList.getSObjectType() : newList.getSObjectType();
    }

    public static void disableAllTriggerActions() {
        disableAllActions = true;
    }

    public static void enableAllTriggerActions() {
        disableAllActions = false;
    }

    public static void disableTriggerAction(Id actionId) {
        disabledActions.add(actionId);
    }

    public static void enableTriggerAction(Id actionId) {
        disabledActions.remove(actionId);
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    @TestVisible
    private static List<Trigger_Action__mdt> getTriggerActionMetadata(
        Schema.SObjectType objectType,
        System.TriggerOperation operationType
    ) {
        if (SPECIAL_SOBJECT_TYPES.contains(objectType)) {
            return [
                SELECT Id, Namespace__c, Apex_Class_Name__c, Invoke_Order__c, Trigger_Context__c
                FROM Trigger_Action__mdt
                WHERE
                    Is_Active__c = TRUE
                    AND Trigger_Context__c = :String.valueOf(operationType)
                    AND Trigger_Object_Special__c = :String.valueOf(objectType)
                WITH SYSTEM_MODE
                ORDER BY Invoke_Order__c ASC
            ];
        }

        return [
            SELECT Id, Namespace__c, Apex_Class_Name__c, Invoke_Order__c, Trigger_Context__c
            FROM Trigger_Action__mdt
            WHERE
                Is_Active__c = TRUE
                AND Trigger_Context__c = :String.valueOf(operationType)
                AND Trigger_Object__r.QualifiedApiName = :String.valueOf(objectType)
            WITH SYSTEM_MODE
            ORDER BY Invoke_Order__c ASC
        ];
    }
}